---
name: File-Class
version: 0.0.1
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
abstract: Simplifies handling of files in a portable way (Hopefully :-) )
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Clone: 0
  Data::Dumper: 0
  File::Spec: 0
  Scalar::Util: 0
  overload: 0
  version: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
provides:
  File::Class:
    file: lib/File/Class.pm
    version: 0.0.1
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
